const express = require("express");
const router = express.Router();
const { requireLogin, adminMiddleware, uploadS3} = require("../middlewares/requireLogin");
const { addCategory, getCategories, deleteCategory, updateCategory, getCategory} = require("../controllers/category");
router.post("/create", requireLogin, adminMiddleware, uploadS3.single("categoryImage"), addCategory);
router.get("/getcategory", getCategories);
router.delete("/deletecategory/:id", requireLogin, deleteCategory);
router.post("/updatecategory/:id", requireLogin, uploadS3.single("categoryImage"), updateCategory);
router.get("/getcategory/:id", requireLogin, getCategory);
module.exports = router;